# Generated by Django 5.0.1 on 2024-01-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noutbuk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noutbuk',
            name='year_n',
            field=models.IntegerField(),
        ),
    ]
